#!/bin/bash
IF=$1
STATUS=$2

#user-defined variables - network interface and ESSID to monitor, and user to start scripts when all conditions are met
INTERFACE=wlan0
NETWORK=office-network
VPN=tun0
USER=user

export DISPLAY=:0.0
ESSID=$(iwconfig $INTERFACE | sed -rn 's/.*ESSID:\"(.*)\".*/\1/p') #obtain ESSID

# Wait for a specific process to be running before proceeding, e.g nm-applet
wait_for_process() { 
	until (/usr/bin/pgrep -qf "$1"); do
		sleep 3;
	done
}

# Check for collison
check_for_process() { 
	/usr/bin/pgrep -qf $1
}

if [ "$IF" = "$INTERFACE" ] && [ "$STATUS" = "up" ] && [ "$ESSID" = "$NETWORK" ]; then
        wait_for_process nm-applet
        # list of applications and user scripts to be run when conditions are met
        if check_for_process user_script; then
	       /usr/bin/su $USER -c "/bin/bash /home/$USER/bin/user_script.sh"
        fi
        if check_for_process pidgin; then
	       /usr/bin/su $USER -c "/usr/bin/pidgin"
        fi
elif [ "$IF" = "$VPN" ] && [ "$STATUS" = "up" ]; then 
        # really basic support for VPN; if you have multiple VPNs configured, you will need to expand on this
        wait_for_process nm-applet
        if check_for_process user_script; then
               /usr/bin/su $USER -c "/bin/bash /home/$USER/bin/user_script.sh"
        fi	
fi
